name: deploy-application
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version:18
      - name: install dependencies
        uses: npm ci
      - name: execute lint
        uses: npm lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version:18
      - name: install dependencies
        uses: npm ci
      - name: execute tests
        uses: npm test
  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version:18
      - name: install dependencies
        uses: npm ci
      - name: deploy
        uses: run build
